name: WakaTime Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 10 AM CDT
    - cron: "0 15 * * *"

jobs:
  wakatime:
    name: WakaTime Readme
    runs-on: ubuntu-latest
    steps:
      - name: Run WakaTime readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False" 
          SHOW_PROJECTS: "False" 
